import type { ConfidenceLevel } from "@/types/evidence";
import type { RelationshipNodeRef } from "@/types/relationship";

/**
 * The generic Event model (Sprint 4.5), per `docs/architecture/DIGA-CORE-ARCHITECTURE-V2.md`.
 * One shape for every fact the platform records — no `RequirementEvent`,
 * `DecisionEvent`, `DiscussionEvent`, etc. Events describe change; the
 * Knowledge Graph (repositories) remains the source of truth for current
 * state. This is a transactional-outbox model, not Event Sourcing: nothing
 * is ever reconstructed purely by replaying events.
 */

export type EventActorType = "person" | "system" | "integration";

/**
 * `id` is `null` for facts not yet attributable to a specific person (e.g.
 * a relationship created before real authentication exists) — `type` still
 * distinguishes a human action from a system-originated one, which is what
 * "AI proposes, humans approve" depends on being auditable, not assumed.
 */
export type EventActor = {
  type: EventActorType;
  id: string | null;
};

/**
 * `"internal"` events are system/audit bookkeeping never shown in a
 * human-facing projection (e.g. a future Timeline). `"project"` events are
 * visible to anyone with access to that Project. This is the significance
 * filter the Timeline projection (`lib/events/timeline-projection.ts`) uses.
 */
export type EventVisibility = "internal" | "project";

export type Event = {
  id: string;
  /** Open string, namespaced and versioned, e.g. "knowledge_object.created.v1" — growable like `EntityExtractor`'s entity `type`, never a closed enum. */
  eventType: string;
  /** ISO timestamp — when the fact became true. */
  timestamp: string;
  actor: EventActor;
  /** The node this event is primarily about (e.g. the Knowledge Object created, the Discussion started). */
  sourceNode?: RelationshipNodeRef;
  /** The other node, for edge-shaped facts (e.g. a Relationship's nodeB). Absent for single-node facts. */
  targetNode?: RelationshipNodeRef;
  /** Every event should be Project-scoped; optional only because `Discussion` has no `projectId` field yet (a pre-existing gap, not introduced here). */
  projectId?: string;
  /** Small, type-specific supplementary detail — never a full object snapshot or large blob. */
  metadata?: Record<string, unknown>;
  visibility: EventVisibility;
  /** Present only on Intelligence-originated events. */
  confidence?: ConfidenceLevel;
  /** A short, human-readable one-line "why" — distinct from the full `ReasoningResult`, which is too rich/type-specific for a generic event. */
  reason?: string;
  /** Ties together a causally related chain (ingestion → proposal → approval). Not yet populated with real chains this sprint — present in the shape for forward compatibility. */
  correlationId?: string;
  /** The single event that directly produced this one. Same forward-compatibility note as `correlationId`. */
  causationId?: string;
  /** Payload version, independent of the semantic version embedded in `eventType`. */
  schemaVersion: number;
};

/**
 * What a caller provides to `EventPublisher.publish()` — `id`/`timestamp`/
 * `schemaVersion` are always generated by the publisher; `visibility`
 * defaults to `"project"` when omitted.
 */
export type PublishEventInput = Omit<Event, "id" | "timestamp" | "schemaVersion" | "visibility"> & {
  visibility?: EventVisibility;
};
