"use client";

import { AlertTriangle, Check, FileText, MapPin, MessageSquareText, PenLine, X } from "lucide-react";
import type { ReviewPackage, ReviewStatus } from "@/types/review";
import { ConfidenceIndicator } from "./ConfidenceIndicator";
import { PackageProgress } from "./PackageProgress";

const sourceIcons = { "Meeting transcript": MessageSquareText, "Drawing upload": FileText, Agreement: PenLine, "Site visit": MapPin };
const statusStyle: Record<ReviewStatus, string> = { Pending: "text-accent-primary bg-accent-muted", Approved: "text-success bg-success/15", Rejected: "text-text-tertiary bg-surface-tertiary", "Needs attention": "text-warning bg-warning/15" };

export function ReviewPackageCard({ reviewPackage, selected, status, complete, onSelect }: { reviewPackage: ReviewPackage; selected: boolean; status: ReviewStatus; complete: number; onSelect: () => void }) { const Icon = sourceIcons[reviewPackage.source as keyof typeof sourceIcons] ?? FileText; const statusIcon = status === "Approved" ? <Check size={11} /> : status === "Rejected" ? <X size={11} /> : status === "Needs attention" ? <AlertTriangle size={11} /> : null; return <button type="button" onClick={onSelect} className={`w-full rounded-xl border p-4 text-left transition ${selected ? "border-accent-primary/40 bg-accent-muted/60" : "border-transparent hover:bg-surface-tertiary"}`}><div className="flex items-start gap-3"><span className="grid size-8 place-items-center rounded-lg bg-surface-tertiary text-text-secondary"><Icon size={16} /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="truncate text-[13px] font-medium text-text-primary">{reviewPackage.title}</span><span className={`grid size-5 place-items-center rounded-full ${statusStyle[status]}`}>{statusIcon}</span></span><span className="mt-1 block text-[11px] text-text-tertiary">{reviewPackage.source} · {reviewPackage.analyzed}</span></span></div><div className="mt-4 flex items-center justify-between"><ConfidenceIndicator value={reviewPackage.confidence} /><span className="text-[11px] text-text-tertiary">{reviewPackage.objects.length || reviewPackage.summary.requirements + reviewPackage.summary.decisions} objects</span></div>{reviewPackage.objects.length > 0 && <div className="mt-4"><PackageProgress complete={complete} total={reviewPackage.objects.length} /></div>}</button>; }
