"use client";

import { useState } from "react";
import { MessageCircle, Copy, Check } from "lucide-react";
import { buildInviteShareLinks } from "@/lib/invitations/share-links";

/**
 * Sprint 5.8, Module 2: the invitation experience is user-facing actions,
 * not implementation details — no invite code, no raw URL, no internal id
 * is ever rendered. Exactly two actions: Copy Invitation Link (copies the
 * real URL to the clipboard without ever displaying it) and Share on
 * WhatsApp (opens a real `wa.me` deep link addressed to the invitee's own
 * number). SMS/Email links are still generated by `buildInviteShareLinks`
 * for architecture-compatibility with a future provider, just not
 * surfaced as buttons here per the brief's own explicit button list.
 */
export function InviteShareSheet({ inviteCode, projectName, roleName, inviteeName, whatsappNumber }: { inviteCode: string; projectName: string; roleName: string; inviteeName?: string | null; whatsappNumber?: string | null }) {
  const [copied, setCopied] = useState(false);
  const links = buildInviteShareLinks({ inviteCode, projectName, roleName, inviteeName, whatsappNumber });

  async function copyLink() {
    try {
      await navigator.clipboard.writeText(links.url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  }

  return (
    <div className="mt-3 rounded-xl border border-border-subtle bg-surface-secondary p-4">
      <p className="text-xs font-medium text-text-tertiary">Invitation ready{inviteeName ? ` for ${inviteeName}` : ""}</p>
      <div className="mt-3 flex flex-wrap gap-2">
        <button type="button" onClick={copyLink} className="flex items-center gap-1.5 rounded-full border border-border-subtle px-3 py-1.5 text-xs font-medium text-text-secondary transition hover:border-accent-primary hover:text-text-primary">
          {copied ? <Check size={14} /> : <Copy size={14} />}
          {copied ? "Copied!" : "Copy Invitation Link"}
        </button>
        <a href={links.whatsapp} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 rounded-full bg-accent-primary px-3 py-1.5 text-xs font-medium text-white transition hover:opacity-90">
          <MessageCircle size={14} />
          Share on WhatsApp
        </a>
      </div>
    </div>
  );
}
